name: Selenium Python Script

on:
    schedule:
        - cron:  '0,45 0/2 * * *' # At minute 0 and 45 past every 2nd hour
        - cron:  '30 1/2 * * *' # At minute 30 past every other 2nd hour    
  workflow_dispatch:

jobs:
  run-selenium-script:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Setup Firefox and Geckodriver
      run: |
        choco install firefox
        choco install selenium-gecko-driver

    - name: Run the Selenium script
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      run: python emailNotification.py
