name: Selenium Python Script

on:
  schedule:
    - cron: '0 * * * *' # This will run the job at the start of every hour
  workflow_dispatch:

jobs:
  run-selenium-script:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests  # hashlib, smtplib, and email are part of the Python standard library and do not need to be installed

    - name: Setup Firefox and Geckodriver
      run: |
        choco install firefox
        choco install selenium-gecko-driver

    - name: Run the Selenium script
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Renamed secret without the 'GITHUB_' prefix
        GIST_ID: ${{ secrets.GIST_ID }}            # Make sure to add this secret in your repository settings
      run: python emailNotification.py
